### ISSUE TITLE
ConvertToAudio Function not Functional

### ISSUE THREAD

**Issue by Sia-WRWD** [Diskordlit/ClassInsight#3]
Assigned to @ConquerorFY , danke

**Comment by ConquerorFY** [comment]
1. Run "npm install video-to-audio" from CLI
2. ![image](https://github.com/Diskordlit/ClassInsight/assets/47184257/3c0a2454-8ea3-46a8-a532-2243823b9396)
    Navigate to this directory
3. ![image](https://github.com/Diskordlit/ClassInsight/assets/47184257/7ae74a4b-883a-40e4-8289-e0508f61eefe)
    Change the first line (module.exports.convert) to the code shown in the snippet.
